name: Backend Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv
    
    - name: Install dependencies
      run: |
        cd backend
        uv sync
    
    - name: Lint with ruff
      run: |
        cd backend
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Run tests
      run: |
        cd backend
        uv run pytest -v 